# - One or more filenames or glob patterns describing local file or files to validate
#   Patterns are resolved relative to the current working directory.
# - overridden by passing one or more positional arguments
patterns: ['*.json']

# - Level of verbose logging. 0 is standard, higher numbers are more verbose
# - overridden by passing --verbose / -v
# - default = 0
verbose: 2

# - Exit with code 0 even if an error was encountered. True means a non-zero exit
#   code is only issued if validation could be completed successfully and one or
#   more files were invalid
# - overridden by passing --ignore-errors
# - default = false
ignoreErrors: false

# - Remove cached HTTP responses older than cacheTtl seconds old.
#   Specifying 0 clears and disables cache completely
# - overridden by passing --cache-ttl
# - default = 600
cacheTtl: 86400

# - Output format for validation results
# - overridden by passing --output-format
# - default = text
outputFormat: "json"

# - A list of files containing glob patterns to ignore
#   Set this to [] to disable all ignore files
# - overridden by passing --ignore-pattern-files or --no-ignore
# - default = [".v8rignore", ".gitignore"]
ignorePatternFiles: []

# - A custom schema catalog.
#   This catalog will be searched ahead of any custom catalogs passed using
#   --catalogs or SchemaStore.org
#   The format of this is subtly different to the format of a catalog
#   passed via --catalogs (which matches the SchemaStore.org format)
# customCatalog:
    # schemas:
        # - name: Custom Schema  # The name of the schema (required)
          # description: Custom Schema  # A description of the schema (optional)

          # A Minimatch glob expression for matching up file names with a schema (required)
          # Expressions are resolved relative to the current working directory.
          # fileMatch: ["*.geojson"]

          # A URL or local file path for the schema location (required)
          # Unlike the SchemaStore.org format, which has a `url` key,
          # custom catalogs defined in v8r config files have a `location` key
          # which can refer to either a URL or local file.
          # Relative paths are resolved relative to the current working directory.
          # location: foo/bar/geojson-schema.json

          # A custom parser to use for files matching fileMatch
          # instead of trying to infer the correct parser from the filename (optional)
          # This property is specific to custom catalogs defined in v8r config files
          # parser: json5

# - An array of v8r plugins to load
# - Plugins can only be specified in the config file.
#   They can't be loaded using command line arguments
plugins:
    # Plugins installed from NPM (or JSR) must be prefixed by "package:"
    - "package:v8r-plugin-emoji-output"
